### ISSUE TITLE
Gradient has outdated syntax

### ISSUE THREAD

**Issue by google-mac** [astrit/css.gg#13]
The new syntax is like `closest-side at 0 0` instead of `0 0, closest-side`.

This will show up in users' terminals if they're using `postcss-loader` or any other package that does evaluation.

**Comment by astrit** [comment]
Thank you for reporting this, I am working on it. 
If you have any suggestion please let me know.

**Comment by astrit** [comment]
@google-mac I have pushed a new version which address this issue please update and let me know if it works for you.

**Comment by google-mac** [comment]
I'm getting the same error still. Perhaps it's happening in the compression?

![Annotation 2020-01-14 120612](https://user-images.githubusercontent.com/17652149/72374155-f3cdd980-36c6-11ea-9dda-afa2c51c8727.png)

Honestly, it's not impairing anyone's workflow, so don't feel like you have to put too much time into it. :)

**Comment by astrit** [comment]
> I'm getting the same error still. Perhaps it's happening in the compression?

**Comment by astrit** [comment]
@google-mac released the version v1.0.6 and if you update it should work since dribbble icon had the old radial gradient syntax, thanks for the last report back.

**Comment by google-mac** [comment]
Thanks!
